services:
  - type: web
    name: digihealth-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: digihealth-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: digihealth-db
          property: password

      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: digihealth-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: digihealth-db
    plan: free
    databaseName: digihealth
    user: digihealth
